language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

    - sys-img-armeabi-v7a-android-25
    - sys-img-armeabi-v7a-android-16

script:
  - ./gradlew build connectedCheck

before_install:
  - chmod +x gradlew