language: java

before_install:
    # Install base Android SDK
    - sudo apt-get update -qq
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
    - wget http://dl.google.com/android/repository/tools_r25.2.3-linux.tgz
    - tar xzf tools_r25.2.3-linux.tgz
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

    # install android build tools
    - wget https://dl-ssl.google.com/android/repository/build-tools_r25.0.2-linux.zip
    - unzip build-tools_r25.0.2-linux.zip -d $ANDROID_HOME
    - mkdir -p $ANDROID_HOME/build-tools/
    - mv $ANDROID_HOME/android-7.1.1 $ANDROID_HOME/build-tools/25.0.2

    # Install required Android components.
    - echo y | android update sdk --filter platform-tools,android-25,extra-android-support,extra-android-m2repository --no-ui --force

script:
    - ./gradlew assemble

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.android/build-cache